config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root "quizzes#index"

  resources :quizzes, except: [:show]
  resources :user_quiz_sessions
  get 'quizzes/:permalink', to: 'quizzes#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :choices
  has_one :answer, -> { where(is_correct: true) }, class_name: 'Choice'


  validates :text, uniqueness: :true

  def is_choice_correct?(choice_id)
    choices.find(choice_id).is_correct?
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :questions
  has_many :user_quiz_sessions
  has_many :users, through: :user_quiz_sessions

  attr_accessor :user_id

  before_create :generate_unique_permalink
  after_update_commit :broadcast_start_quiz, if: :saved_change_to_active?

  def generate_unique_permalink
    self.permalink = SecureRandom.uuid
  end

  def broadcast_start_quiz
    if active
      broadcast_replace partial: 'shared/quiz/quiz_start',
                        locals: { question: questions.first, user_quiz_session: user_quiz_session },
                        target: 'quiz-menu'
    else
      broadcast_replace partial: 'shared/quiz/quiz_waiting', locals: { quiz: self }, target: 'quiz-menu'
    end

    broadcast_append_to 'reset', partial: 'shared/quiz/reset_quiz', target: 'reset', locals: { quiz: self }
  end

  def next_question(question)
    position = questions.find(question).position

    questions.where("position > ?", position).first
  end

  def user_quiz_session
    user_quiz_sessions.find_by(user_id: user_id)
  end

  def user
    User.find_by(id: user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_quiz_sessions
  has_many :quizzes, through: :user_quiz_sessions

  validates :first_name, :last_name, :email, presence: :true
  validates :email, uniqueness: :true

  def name
    "#{first_name} #{last_name}"
  end

  def score
    # TODO: Add logic
    10
  end

  def won
    # TODO: Add logic
    false
  end
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user_quiz_session
  belongs_to :question
  belongs_to :choice
end

app/models/user_quiz_session.rb
class UserQuizSession < ApplicationRecord
  belongs_to :user
  belongs_to :quiz

  attr_accessor :current_question

  after_create_commit do
    broadcast_append_to quiz, partial: 'shared/leaderboard/item',
                     locals: { user: user, highest: false },
                     target: 'users-list'
  end

  after_update_commit do
    broadcast_replace_to quiz, partial: 'shared/leaderboard/list',
                      locals: { data: quiz.user_quiz_sessions.order('score DESC') },
                      target: 'user_quiz_sessions'
  end

  after_update_commit do
    broadcast_replace_to user,
                         partial: 'shared/quiz/quiz_start',
                         locals: { question: quiz.next_question(current_question) , user_quiz_session: self },
                         target: 'quiz-start'
  end

  def update_score(new_points)
    total_score = score + new_points
    update(score: total_score)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {
      |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)
    }
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_quiz, only: [:show]
  before_action :find_or_create_quiz_session, only: [:show]
  before_action :destroy_user_quiz_sessions, only: [:index]

  skip_before_action :verify_authenticity_token, only: [:update]

  def index
    @quizzes = Quiz.all.order(created_at: :asc)
  end

  def show
    @user_quiz_sessions = @quiz.user_quiz_sessions.order('score DESC')
    @user_quiz_session = current_user.user_quiz_sessions.find_by(quiz_id: @quiz.id)
    @user = current_user
  end

  def update
    quiz = Quiz.find(params[:id])

    case params[:commit]
    when 'start'
      quiz.update(active: true, user_id: current_user.id)
    when 'reset'
      quiz.update(active: false, user_id: nil)
      quiz.user_quiz_sessions.destroy_all
      redirect_to root_path
    end
  end

  private

  def fetch_quiz
    @quiz = Quiz.find_by!(permalink: params[:permalink])
  end

  def find_or_create_quiz_session
    UserQuizSession.find_or_create_by!(user: current_user, quiz: @quiz)
  end

  def destroy_user_quiz_sessions
    current_user.user_quiz_sessions.destroy_all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:landing_pages]

  def landing_pages
  end

  def dashboard
  end
end

app/controllers/user_quiz_sessions_controller.rb
class UserQuizSessionsController < ApplicationController
  before_action :authenticate_user!

  def update
    user_quiz_session = UserQuizSession.find(params[:id])
    question = user_quiz_session.quiz.questions.find(uqs_params[:question][:id])
    user_quiz_session.current_question = question.id
    is_correct?(question) ? user_quiz_session.update_score(question.points) : user_quiz_session.touch
  end

  private

  def is_correct?(question)
    choice_id = uqs_params[:question][:choice][:id]
    question.is_choice_correct?(choice_id)
  end

  def uqs_params
    params.require(:user_quiz_session).permit(
      question: [:id, choice: [:id]]
    )
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :destroy_user_quiz_sessions, only: :destroy

  def destroy_user_quiz_sessions
    current_user.user_quiz_sessions.destroy_all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current(question)
    question.position
  end

  def total(user_quiz_session)
    user_quiz_session.quiz.questions.count
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizTurbo</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;500&display=swap" rel="stylesheet">
</head>

<body>
<% if alert %>
  <%= render 'shared/snackbar', { msg: alert } %>
<% end %>
<% if notice %>
  <%= render 'shared/snackbar', { msg: notice } %>
<% end %>

<%= yield %>
</body>
</html>

app/views/quizzes/index.html.erb
<div class="quiz-wrapper">
  <%= render 'shared/user_drawer', { quiz: @quiz } %>
  <%= render 'shared/quiz/list', { quizzes: @quizzes } %>
</div>

app/views/quizzes/show.html.erb
<div class="quiz-wrapper">
  <%= render 'shared/user_drawer', { quiz: @quiz } %>
  <%= render 'shared/quiz/decide', { quiz: @quiz, user: @user } %>
  <%= render 'shared/leaderboard/leaderboard', { user_quiz_sessions: @user_quiz_sessions } %>
</div>

app/views/shared/_badge.html.erb
<div class="badge">
  <span class="badge-wrap">
    <span class="badge-icon">
      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14">
        <path d="M7 2.333c2.577 0 4.667 2.09 4.667 4.667S9.577 11.667 7 11.667 2.333 9.577
          2.333 7 4.423 2.333 7 2.333zm0 1.05c-1.997 0-3.617 1.62-3.617 3.617 0 1.997 1.62
          3.617 3.617 3.617 1.997 0 3.617-1.62 3.617-3.617 0-1.997-1.62-3.617-3.617-3.617z">
        </path>
      </svg>
      <span class="badge-icon-inner">
        <svg aria-hidden="true" focusable="false" viewbox="0 0 14 14">
          <path d="M7 9.567c1.418 0 2.567-1.15 2.567-2.567 0-1.418-1.15-2.567-2.567-2.567-1.418
           0-2.567 1.15-2.567 2.567 0 1.418 1.15 2.567 2.567 2.567z">
          </path>
        </svg>
      </span>
    </span>
    <span class="badge-text"> LIVE </span>
  </span>
</div>

app/views/shared/_logo.html.erb
<pre class="logo">

╭━━╮╱╭┳━╮╱╱╭╮╭╮
┃╭╮┣┳╋╋━┣━╮┃╰┫╰┳━┳━┳╮
┃╰╯┃┃┃┃━┫╋╰┫╭┫┃┃╋┃┃┃┃
╰━╮┣━┻┻━┻━━┻━┻┻┻━┻┻━╯
╱╱╰╯
</pre>

app/views/shared/_snackbar.html.erb
<div id="snackbar" data-controller="snackbar" data-snackbar-target="toast">
  <span class="material-icons">
    info
  </span>
  <%= msg %>
</div>

app/views/shared/_user_drawer.html.erb
<div class="user">
  <div class="name">
    <span class="avatar"><img src="https://avatars.dicebear.com/api/pixel-art/<%=current_user.id%>.svg"/></span>
    <span><%= current_user.name %></span>
  </div>
  <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
    <button class="exit">
      <span>Exit</span>
      <span class="material-icons">
      logout
    </span>
    </button>
  <% end %>

  <%= turbo_stream_from 'reset' %>
  <%= render 'shared/quiz/reset_quiz', quiz: quiz %>
</div>

app/views/shared/leaderboard/_item.html.erb
<% className = "rank-item card" %>
<% className << " first" if highest %>

<div class="<%= className %>">
  <span class="material-icons">
  <% if highest %>
    military_tech
  <% else %>
    run_circle
  <% end %>
  </span>
  <span class="name"><%= user_quiz_session.user.name %></span>
  <span class="score"><%= user_quiz_session.score %></span>
</div>

app/views/shared/leaderboard/_leaderboard.html.erb
<div class="leaderboard card">
  <div class="leaderboard-header">
    <span class="leaderboard-title">Leaderboard</span>
    <%= render 'shared/badge' %>
  </div>
  <%= turbo_stream_from user_quiz_sessions %>
  <%= render 'shared/leaderboard/list', { data: user_quiz_sessions } %>
</div>

app/views/shared/leaderboard/_list.html.erb
<%= turbo_frame_tag 'user_quiz_sessions' do %>
  <div class="rank-list" , id="users-list">
    <% data.each_with_index do |user_quiz_session, index| %>
      <%= render 'shared/leaderboard/item', { user_quiz_session: user_quiz_session, highest: index == 0 && user_quiz_session.score > 0 } %>
    <% end %>
  </div>
<% end %>

app/views/shared/quiz/_answer.html.erb
<button class="answer card">
  <%= choice.text %>
</button>

app/views/shared/quiz/_decide.html.erb
<%= turbo_stream_from quiz %>
<%= turbo_stream_from user %>

<div class="quiz-menu">
  <% if quiz.active %>
    <%= render 'shared/quiz/quiz_start', { question: quiz.questions.first, user_quiz_session: @user_quiz_session } %>
  <% else %>
    <%= render 'shared/quiz/quiz_waiting', { quiz: quiz } %>
  <% end %>
</div>

app/views/shared/quiz/_list.html.erb
<div class="quiz card">
  <div class="list-title">
    <%= render 'shared/logo' %>
  </div>
  <div class="list">
    <% quizzes.each do |quiz| %>
      <%= render "shared/quiz/quiz_type", { quiz: quiz } %>
    <% end %>
    <div class="quiz-selection">
      Coming soon!
    </div>
  </div>
</div>

app/views/shared/quiz/_question.html.erb
<div class="question card">
  <span class="material-icons">
    psychology_alt
  </span>
  <span>
    <%= question.text %>
  </span>
</div>

app/views/shared/quiz/_quiz_start.html.erb
<%= turbo_frame_tag 'quiz-start', class: 'extend' do %>
  <div class="quiz card" id="quiz-menu">
    <span class="material-icons timer">timer</span>
    <div class="question-collection">
      <% if question.present? %>
        <%= render "shared/quiz/question", { question: question } %>
        <div class="answer-collection">
          <% question.choices.each do |choice| %>
            <%= form_with model: user_quiz_session do |user_quiz_session| %>
              <%= user_quiz_session.fields_for :question do |question| %>
                <%= question.fields_for :choice do |f| %>
                  <span class="answer card">
                    <%= question.hidden_field :id, value: choice.question.id %>
                    <%= f.hidden_field :id, value: choice.id %>
                    <%= f.submit choice.text %>
                  </span>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="remaining-count">
          <span class="current"><%= current(question) %></span>
          /
          <span class="total"><%= total(user_quiz_session) %></span>
        </div>
      <% else %>
        <div class="thank-you">
          Finished!
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/quiz/_quiz_type.html.erb
<div class="quiz-selection">
  <%= quiz.title %>
  <%= link_to quiz_path(quiz.permalink) do %>
    <button class="exit">
      <span>Start</span>
      <span class="material-icons">
      sports_score
    </span>
    </button>
  <% end %>
</div>

app/views/shared/quiz/_quiz_waiting.html.erb
<div class="quiz wait card" id="quiz-menu">
  <%= image_tag "quiz.svg" %>
  <div class="content">
    <span class="title"><%= quiz.title %></span>
    <div class="desc-wrapper">
      <span class="desc">Share the link for a multiplayer game.</span>
      <span class="desc">Starting the quiz will start for all players.</span>
    </div>
    <div class="action-items">
      <%= form_with model: quiz do |f| %>
        <button type="submit" class="start" name="commit" value="start">
          <span>Start Quiz</span>
          <span class="material-icons">
          flight_takeoff
        </span>
        </button>
      <% end %>

      <button type="secondary" class="copy" data-controller="clipboard" data-clipboard-target="action" data-action="clipboard#copy">
        <span>Copy link</span>
        <span class="material-icons">
          content_paste
        </span>
      </button>
    </div>
  </div>
</div>

app/views/shared/quiz/_reset_quiz.html.erb
<div id="reset">
  <% if quiz&.active %>
    <%= form_with model: quiz, data: { turbo: false } do %>
      <button class="back" type="submit" name="commit" value="reset">
        <span>Reset</span>
        <span class="material-icons">
          restart_alt
        </span>
      </button>
    <% end %>
  <% end %>
</div>